First iteration of summary rollup.
BU-NU-CLOUD-F19/MOC_Reporting pull request #19
Opened 2019-10-31 05:58 UTC by kevinliang43

Example Raw Data:
![image](https://user-images.githubusercontent.com/15353453/67922640-b35bc680-fb81-11e9-8d7a-215b11869ee8.png)

Example Aggregated Data:
![image](https://user-images.githubusercontent.com/15353453/67922657-c078b580-fb81-11e9-9205-aace1ff41bd3.png)

First Iteration. Still need to add support for `Month` in our aggregations. As of now, we can support periods of 'day', and 'week' for our aggregations

2019-10-31 21:37 UTC, kevinliang43 commented
Issue with Bill.sql schema for `raw_item_ts`: https://github.com/BU-NU-CLOUD-F19/MOC_Reporting/issues/22

Holding off from merging/reviewing for now.

2019-11-12 21:35 UTC, tsachleben commented
Issue #22 fixed by #23

2019-11-15 03:12 UTC, kevinliang43 commented
Added functionality for monthly aggregations. Refactored aggregations to be on `item_id` rather than `catalog_item_id`. 

Merging of this PR is dependent on this PR being merged first: https://github.com/BU-NU-CLOUD-F19/MOC_Reporting/pull/25

2019-11-15 03:49 UTC, tsachleben reviewed
Will want to discuss in-person

2019-11-19 21:02 UTC, tsachleben commented on summary_rollup.py
> +    if len(raw_item_ts_rows) > 0:
Add edge condtion:

> if raw_item_ts_rows is not None and len(raw_item_ts_rows) > 0:

2019-11-19 21:02 UTC, anju-james submitted a review, later dismissed
Good to merge once the comments above are addressed.

2019-11-19 21:04 UTC, tsachleben commented on summary_rollup.py
> +        execute_query(cur, query.format(item_id, start_date, catalog_item_id, state, end_date, period, time))
Need to be able to signal to top level when a write has failed.

2019-11-19 21:05 UTC, tsachleben requested changes
See comments in code

2019-11-25 04:24 UTC, kevinliang43 commented
Added edge case check for querying raw_item_ts rows.

Added signaling to top level when reads/writes fail.

2019-11-25 14:44 UTC, anju-james approved these changes
LGTM

2019-11-25 21:54 UTC, tsachleben approved these changes

2019-11-25 21:55 UTC, merged