Update for Primary Keys in raw_item_ts and summarized_item_ts
BU-NU-CLOUD-F19/MOC_Reporting pull request #25
Opened 2019-11-12 23:25 UTC by kevinliang43

Condensed primary key updates for `raw_item_ts` into a single line.

Added primary key fields for `summarized_item_ts`

2019-11-14 05:17 UTC, tsachleben approved these changes

2019-11-15 03:12 UTC, kevinliang43 commented
Added functionality for monthly aggregations. Refactored aggregations to be on `item_id` rather than `catalog_item_id`. 

Merging of this PR is dependent on this PR being merged first: https://github.com/BU-NU-CLOUD-F19/MOC_Reporting/pull/25

2019-11-19 21:03 UTC, anju-james submitted a review, later dismissed
LGTM

2019-11-19 21:07 UTC, tsachleben requested changes

2019-11-19 21:07 UTC, tsachleben commented on bill.sql
> +                CONSTRAINT raw_item_ts_pk PRIMARY KEY (item_id, start_ts, end_ts)
Drop end_ts from PK

2019-11-25 13:55 UTC, anju-james approved these changes

2019-11-25 21:52 UTC, tsachleben approved these changes

2019-11-25 21:52 UTC, merged