Script to migrate data from old DB to new DB schema
BU-NU-CLOUD-F19/MOC_Reporting pull request #26
Opened 2019-11-14 02:40 UTC by anju-james

Script to extract and transport data from old moc_billing DB to new moc_reporting DB with a different schema.

Test steps:
- Connect to old and Db and new Db
- Connecting to old Db by hardcoding the db name, host, username and password in main method
- Run script: python3 data_migrator.py 
- You should see the test data in new DB schema

2019-11-18 06:29 UTC, kevinliang43 commented on data_migrator.py
> +    #etl.todb(role_transformed, to_db_conn, 'role')
Is this commented-out block of code necessary to keep into the final script?

2019-11-19 21:10 UTC, tsachleben requested changes

2019-11-19 21:10 UTC, tsachleben commented on data_migrator.py
> +    source_db_config = {"dbname":"", "host":"", "user": "", "pass": ""}
Put a comment here explaining that this object represents the config/auth to the older Database and needs to be filled in once before running the code.

2019-11-19 21:17 UTC, anju-james commented on data_migrator.py
> +    source_db_config = {"dbname":"", "host":"", "user": "", "pass": ""}
Added the comment.

2019-11-21 19:32 UTC, rob-baron approved these changes
This is a reasonable start.

2019-11-21 19:32 UTC, robbaronbu commented on data_migrator.py
> +    3. role table is already populated in bill.sql file so that table is skipped by this script
Should confirm that roles are the same/...

2019-11-21 19:32 UTC, robbaronbu commented on data_migrator.py
> +    6. project2moc_project.username is not available from old schema so currently set to empty
I split the project2poc table into project2poc and project2moc_poc.  Different information has to go into the tables.

2019-11-25 13:51 UTC, anju-james reviewed
N.B
- The test data we were provided did not contain the datas or tables for poc_role and project2poc containing any role related information. So we are unable to confirm if the roles the same in old and new data. 
- The different information(username and role_id) to go into  the poc2project and poc2moc_project are currently not available from test data as poc2project table was not provided in test data.

2019-11-25 21:49 UTC, tsachleben approved these changes

2019-11-25 21:49 UTC, merged